### ISSUE TITLE
issue with nvim integration

### ISSUE THREAD

**Issue by cova-fe** [ndonfris/fish-lsp#22]
HI all, 
first of all thanks for this project, really appreciate it. 
Now, for my issue: I'm integrating fish-lsp in neovim by means of nvim-lspconfig and mason. I already put together a draft that works (of course locally, I will open a PR with the respective repos once working, if no one did that before me :) ) but when I run :lua vim.lsp.buf.format { async = true } to format a fish file, like I do for all others languages, the formatting happens but I get also a prompt that disrupts the workflow. Example:
![image](https://github.com/ndonfris/fish-lsp/assets/385249/40e0dc47-c8e3-4207-a450-7c285b193271)
I'm not really understanding the "44 files" and the prompt. To proceed I need to press enter.
My setup:
macosx M3 apple silicon
nvim 0.9.5
lspconfig:

`  default_config = {
    cmd = { 'fish-lsp', 'start' },
    filetypes = { 'fish' },
    root_dir = util.root_pattern('config.fish', '$HOME/.config/fish'),
    single_file_support = true,
    init_options = {},
  },
`
Maybe the issue comes from the root_dir setup, but my fiddling around did not improve the situation so far.
It is the first time that I create a lsp config for the  the whole chain (lspconfig/mason-registry/mason-lspconfig/mason) so it could be that I made some silly mistake.

**Comment by cova-fe** [comment]
> Hi! Thanks for the kind words. Sorry for the delayed response, I was traveling when you posted this, and have since been quite busy. As for your issue, I have a couple questions about the expected behavior _(sorry, I don't use mason and my config is largely vimscript)_.

No problem, I was traveling as well... My setup is basically vimscript free, good testing ground then :)
> 
> 1. When you run the format command, is it formatting all of your fish config?

Nope, only the file in the current buffer (as expected). The issue is basically not the message itself, but the fact that a key press is required to proceed. Example:
![image](https://github.com/ndonfris/fish-lsp/assets/385249/85a7837e-793f-4bb6-8f2e-9de4e35cab99)


> 2. Does that same `analyzed 44 files after 0.188 seconds` message show up at startup? Heres what my message displays when I startup the lsp and the filesystem has been indexed:

Yes, it shows up at startup. I'm not sure which files lsp is analyzing, as adding one more file in .config/fish folder does not change the number shown.  However, the problem is not the message shown, but the fact that it requires to press a key to proceed. Also the "Type number and <Enter>" part is a bit confusing: what it means "Type number"?

>    > This is intended to display that the filesystem has been properly indexed and can now provide documentation/etc.
> 3. Can you confirm that the installation process is indeed working on macos now? There was a couple prior issues that mentioned difficulties installing (That I've hoped to now fix on macos)

In my case I had no issues, tbh. Will keep an eye, just in case :)

> 4. Is the `root_dir` key required in the table of the lsp config for mason? I'm currently working on a PR that will just read in the fish workspace's from a user's shell env.

It is not a problem having the root_dir parameter in config, probably it makes things more visible and uniform than a shell env, I was just wondering if this parameter can have an effect on the "scanning" that happens at start.

> 
> In your `~/.config/nvim/lua` config:
> 
> ```lua
> default_config = { 
>  cmd = { 'fish-lsp', 'start' },
>  filetypes = { 'fish' }, 
>  -- root_dir = util.root_pattern('config.fish',
>  -- '$HOME/.config/fish'),
>  single_file_support = true,
>  init_options = {},
> },
> ```
> 
> Then in `~/.config/fish/config.fish`:
> 
> ```fish
> # fish_lsp_all_indexed_paths <ARRAY>
> # fish file paths to include as workspaces (default: ['/usr/share/fish',
> # '$HOME/.config/fish'])
> set -gx fish_lsp_all_indexed_paths '/usr/share/fish' "$HOME/.config/fish"
> 
> # fish_lsp_modifiable_paths <ARRAY>
> # fish file paths that can be renamed by the user (default:
> # ['$HOME/.config/fish'])
> set -gx fish_lsp_modifiable_paths "$HOME/.config/fish"
> ```
> 
> I'm wondering if you think this would resolve the issue, or if you had a better idea for resolving the issue since you're more familiar with mason.

Will have a look at your suggested configs asap, many thanks!

**Comment by ndonfris** [comment]
@cova-fe 

> 1. Nope, only the file in the current buffer (as expected). The issue is basically not the message itself, but the fact that a key press is required to proceed. Example: ![image]

Okay that's good to hear! The prior release of the formatter was a little buggy for selection ranges, has been updated to fix minor formatRange one off errors. Wanted to make sure it wasn't breaking your config though.
___

> 2. Yes, it shows up at startup. I'm not sure which files lsp is analyzing, as adding one more file in .config/fish folder does not change the number shown. However, the problem is not the message shown, but the fact that it requires to press a key to proceed. Also the "Type number and " part is a bit confusing: what it means "Type number"?

Gotcha. I assume this is probably something to do with differing configurations between how the notifications are displayed. In my [nvim-notify](https://github.com/rcarriga/nvim-notify) config I reveal the messages on the `info` channel, which could possibly be one reason that I don't get the same issue locally. If mason allows for an option equivalent to `"revealOutputChannelOn": "info",`, this could also possibly resolve the prompting behavior seen. 

I agree that the message outputted is confusing, and will continue looking for the cause the of it. 

My client doesn't show any "Type number" prompt, so another thing I plan on trying to fix this is sending client `this.connection.window` messages differently. 

___

> 3. Yes, it shows up at startup. I'm not sure which files lsp is analyzing, as adding one more file in .config/fish folder does not change the number shown. 

So, the lsp analyzes lazily loaded files from your fish config. It is analyzing the files that would be relevant to fish's configuration (i.e., `fish/functions/`, `fish/completions/`, and `config.fish`).
  > this is `definition` and `references` are created by the file system analysis.   

In the example provided using `config2.fish`, I don't think fish would load it into the env. So, while the lsp can be used on external scripts, it currently doesn't use them in the analysis step. 

___

> 4. It is not a problem having the root_dir parameter in config, probably it makes things more visible and uniform than a shell env, I was just wondering if this parameter can have an effect on the "scanning" that happens at start. 

So, one of the issues I've kind of hinted at in the previous sections (and what has been very challenging while building this project), is that definitions and other symbol definitions in fish are ambiguous (i.e., you can set a variable multiple times globally, you can overwrite a command with a function, etc.). So if you want to rename one of those ambiguous definitions, the lsp needs to be able to know which scopes are valid. 

This is why the newer release includes two variables for where to lookup fish workspaces. 

The new configuration includes the variables `fish_lsp_max_background_files`, `fish_lsp_modifiable_paths`, and `fish_lsp_all_indexed_paths`. All of these files should have an effect on the startup scanning.

I also thought its worth mentioning that your screenshots provided don't use the shared fish environment (`/usr/share/fish` on linux). If you installed fish using `homebrew`, they are probably in a different location like: `/usr/local/Cellar/fish/3.7.1/share/fish/`

**Comment by ndonfris** [comment]
Thanks @mimikun for the config files. I'll try to use them to recreate the setup with this problem and get back to y'all.

Not sure how long this will take for me. If you're up for it, forking the [fish-lsp-language-clients](https://github.com/ndonfris/fish-lsp-language-clients) repo, and submitting a PR including a minimal neovim client using your mason and null-ls would be awesome.

**Comment by cova-fe** [comment]
Thanks, that fixed the issue on my side. Basic config has been added to nvim-lspconfig nvim module. https://github.com/neovim/nvim-lspconfig/commit/6dfb2463e3351359fe6d6a902ac06857b3d7ed20
