### ISSUE TITLE
you beat me to a (near) full implementation

### ISSUE THREAD

**Issue by TheBearodactyl** [ndonfris/fish-lsp#29]
i started my own implementation of a fish language server about 1-2 weeks ago, it seems i have failed :trollface:

Anyways, i was wondering if you might wanna use my version at some point to make a faster and more reliable implementation (since my implementation is written completely in Rust)?

**Comment by TheBearodactyl** [comment]
nvm, it didn't show the commit count and i thought this was new lol

**Comment by ndonfris** [comment]
Yeah, I've put in a lot of work on this project :rofl: it's not new. I'd especially encourage you to contribute here if you're interested in providing fish with a feature rich LSP. 

__I would be open to a rewrite in rust eventually.__ My current plan is actually to follow the official fish team's footsteps of producing a working extensive feature set, then rewriting the entire project. 

There are still many [more advanced features](https://github.com/ndonfris/fish-lsp/blob/master/docs/ROADMAP.md) that I want to implement first. Once they are done, a rewrite will be significantly easier. 

Please feel free to contribute here, as I am very much looking for help from the community. IMO, more community support is the best way to ensure to reliability for LSP's. This is actually why many of the feature's that are marked as [not supported](https://github.com/ndonfris/fish-lsp/tree/master#features), are actually partially working/implemented.    

As the project matures, we can certainly create a rewrite in rust here, that is focused on efficiency.
