### ISSUE TITLE
BUG The server interprets the `status` command as `$status` on hover

### ISSUE THREAD

**Issue by kmoschcau** [ndonfris/fish-lsp#31]
**Describe the bug**
When I trigger `textDocument/hover` on `status`, I get the hover result for the `$status` variable instead.

**To Reproduce**
Write this to a file:

```fish
status --is-interactive
echo $status
```

Trigger hover on both `status` and `$status` and observe that they both give the same hover result.

**Expected behavior**
A hover on `status` should give the hover result for the `status` command instead of a variable.

**Screenshots**
N/A

**Please complete the following information:**
```
OS NAME: GNU/Linux
YARN VERSION: 1.22.19
NODE VERSION: v21.6.1
FISH VERSION: fish, version 3.7.1
FISH-LSP VERSION: 1.0.4
```

PS: Nice work on this so far, works rather well. 😄

**Comment by ndonfris** [comment]
Thanks for the kind words! :) 

The package tree-sitter-fish allows for variables to be any of the following types: `word`, `variable_name`, or `variable_expansion`. 

In your example, `status --is-interacte`, hovering the `status` keyword will also be a `word`. 

Will try to fix this specific edge case tonight. In general, improving the test-suite for correctly parsing node-types is something that needs more support if you're interested in contributing.
