### ISSUE TITLE
Where is the lock file ?

### ISSUE THREAD

**Issue by gungun974** [ndonfris/fish-lsp#34]
Hoi !

I recently starting to write some fish script since it's a lot better than bash but I'm missing in my neovim a fish-lsp.

So I stumbled on this project and it's works very well except it's not yet package in nixpkgs. (I'm a Nixos user yeah).

So I wanted to package myself this package but than I realize there is no yarn.lock in this project.

Why don't you commit the lock file ?

**Comment by ndonfris** [comment]
Hi! Glad the project is working well for you :)

It seems like there's a lot of support among nixos users, for this project. I know @jpaju mentioned he was trying to package it himself. 

As for packaging the `yarn.lock`, I initially started this project using npm and then switched to yarn at some point. I will remove the [*.lock entry from .gitignore](https://github.com/ndonfris/fish-lsp/blob/50f377b9c287b8c2c677a76a411d2beec02e56d1/.gitignore#L9), and push it later tonight. 

Good luck with packaging it! Let me know if there's anything I can to do to help!
