### ISSUE TITLE
Can you tag the latest version commit ?

### ISSUE THREAD

**Issue by gungun974** [ndonfris/fish-lsp#39]
Hoi again !

I'm almost done as I said in a previous ticket that I wanted to integrate this package into nixpkgs.

I'm just stumbled something little odd. Your latest commit called `v1.0.6` (9f69887c9113deecc9c301ad23974911be7d942f) don't have any tag !

Could it be possible for you to tag it `v1.0.6` but also in the future tag next version too ?

It make the tracking of the project version simpler.

**Comment by ndonfris** [comment]
__Thanks for working on a nix package for the project!__

Sorry about the missing tag on `v1.0.6`.

In the future, I can certainly keep tagging new releases. Also, I wanted to make sure you saw I tagged the [version](https://github.com/ndonfris/fish-lsp/tree/v1.0.6/) mentioned.

If you're interested in further streamlining methods to distribute this project, I could really use some help building a [github-action](https://github.com/ndonfris/fish-lsp/tree/master/.github/workflows) for releasing the project as a standalone binary (_as seen in_ [json-language-server](https://github.com/zed-industries/json-language-server)).

From my own research, I think that'd probably be the simplest method for tracking and releasing this lsp.

**Comment by ndonfris** [comment]
Since new versions are being tagged, I'm going to close this issue and move the discussion about releases that use a standalone binary to #50
