### ISSUE TITLE
v1.0.8 doesn't include log file changes

### ISSUE THREAD

**Issue by petertriho** [ndonfris/fish-lsp#51]
**Describe the bug**
Looks like v1.0.8 was tagged incorrectly. It doesn't include the log file changes.

**Comment by ndonfris** [comment]
Sorry about that! The tag has been updated on [github](https://github.com/ndonfris/fish-lsp/releases/tag/v1.0.8).

I will republish v1.0.8 on [npm](https://www.npmjs.com/package/fish-lsp), once the time limit is removed (within 24hrs).

**Comment by ndonfris** [comment]
Actually, here is a patched version [v1.0.8-1](https://github.com/ndonfris/fish-lsp/releases/tag/v1.0.8-1):
- [git](https://github.com/ndonfris/fish-lsp/releases/tag/v1.0.8-1)
- [npm](https://www.npmjs.com/package/fish-lsp/v/1.0.8-1)

Please let me know if there are any other issues!

**Comment by petertriho** [comment]
Thanks, don't need to wait for npm since the nix builds pull from github. 

Have the PR ready, just having some issues with the pr checks. Refactored the nix package to use `mkDerivation` + `yarnConfigHook/yarnBuildHook` instead of the old `mkYarnPackage` way. I also don't need the `fish_wasm_file` changes anymore but doesn't hurt just leaving it there. 
https://github.com/NixOS/nixpkgs/pull/330996
