### ISSUE TITLE
Install fails due to --ignore-scripts and --no-progress preinstall options.

### ISSUE THREAD

**Issue by dsully** [ndonfris/fish-lsp#53]
**Describe the bug**
Yarn 4 / 4.4.1 does not have `--ignore-scripts` or  `--no-progress` options as used in the `preinstall` script.

**To Reproduce**
Run `yarn install`

**Expected behavior**
`fish-lsp` is built and installed.

**Please complete the following information:**
 - OS: Darwin
 - yarn version: `4.4.1-git.20240825.hash-b2f315f6`
 - node version: `v20.17.0`
 - fish version `3.7.1`

**Comment by ndonfris** [comment]
Sounds like [corepack](https://nodejs.org/api/corepack.html) would solve this.

If you've cloned the repo for your installation, I think the following command would fix this.

```fish
corepack install yarn@1.22.22
corepack use yarn@1.22.22 
# which yarn
yarn install
```
 
Let me know if that helps!

**Comment by dsully** [comment]
I use `volta` - so I did it that way. Thanks
